name: Daily Repository Sync

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Clone drpy-node repository
        run: |
          # 创建临时目录
          mkdir -p temp_backup
          
          # 保存重要文件
          if [ -d ".git" ]; then
            cp -r .git temp_backup/
          fi
          if [ -d ".github" ]; then
            cp -r .github temp_backup/
          fi
          
          # 清空当前目录
          find . -mindepth 1 -maxdepth 1 ! -name 'temp_backup' -exec rm -rf {} +
          
          # 克隆最新的drpy-node仓库内容到临时目录
          git clone https://github.com/hjdhnx/drpy-node.git temp_clone
          
          # 移动克隆的内容到当前目录
          mv temp_clone/* temp_clone/.* . 2>/dev/null || true
          rm -rf temp_clone
          
          # 还原重要文件
          if [ -d "temp_backup/.git" ]; then
            rm -rf .git
            mv temp_backup/.git ./
          fi
          if [ -d "temp_backup/.github" ]; then
            rm -rf .github
            mv temp_backup/.github ./
          fi
          
          # 清理临时目录
          rm -rf temp_backup
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "Auto sync with drpy-node repository $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main