name   名字: Daily Repository Sync

on:   :
  schedule:   日程安排:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:   工作:
  sync:
    runs-on: ubuntu-latest   运行环境：Ubuntu最新版本
    
    steps:   步骤:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Clone drpy-node repository
        run: |   运行:|
          # 清空当前目录（保留.git和github工作流文件）
          mkdir -p temp_backup
          mv .git temp_backup/
          mv .github temp_backup/
          rm -rf *
          
          # 还原.git和github工作流
          mv temp_backup/.git ./
          mv temp_backup/.github ./
          rm -rf temp_backup
          
          # 克隆最新的drpy-node仓库内容
          git clone https://github.com/hjdhnx/drpy-node.git .
          
      - name: Configure Git
        run: |   运行:|
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Commit and push changes
        run: |   运行:|
          git add -A
          git commit -m "Auto sync with drpy-node repository $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main

